import {
  Atom,
  Boxes,
  Braces,
  Briefcase,
  Calendar,
  Check,
  Clock,
  Code2,
  Component,
  Copy,
  ExternalLink,
  FileCode2,
  FileJson,
  FolderGit2,
  GitBranch,
  GitFork,
  Heart,
  Layers,
  Mail,
  Moon,
  Palette,
  PlugZap,
  Route,
  Search,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Zap,
} from 'lucide-react';
import { GithubIcon, LinkedinIcon, TelegramIcon } from './brandIcons';

const map = {
  github: GithubIcon,
  linkedin: LinkedinIcon,
  telegram: TelegramIcon,
  mail: Mail,
  html: FileCode2,
  css: Palette,
  js: FileJson,
  react: Atom,
  vite: Zap,
  router: Route,
  redux: Layers,
  zustand: Boxes,
  api: PlugZap,
  git: GitBranch,
  mui: Component,
  sparkles: Sparkles,
  zap: Zap,
  code: Code2,
  folder: FolderGit2,
  clock: Clock,
  heart: Heart,
  sun: Sun,
  moon: Moon,
  star: Star,
  fork: GitFork,
  search: Search,
  copy: Copy,
  check: Check,
  external: ExternalLink,
  briefcase: Briefcase,
  calendar: Calendar,
  terminal: Terminal,
  boxes: Boxes,
};

export function getIcon(name) {
  return map[name] || Braces;
}

export const icons = map;